export const profileViewMockTemplate = {
  Name: "Test Template 2",
  DatapointCount: 100,
  Attributes: [
    {
      Version: "0.1",
      Event: "Quote",
      Metadata: "email",
      DisplayName: "Email",
      AggregationMode: "Value",
      type: "tab",
      Limit: 1,
      tag: "email",
    },
    {
      Version: "0.1",
      Event: "Quote",
      Metadata: "Make",
      DisplayName: "Make",
      AggregationMode: "Value",
      Limit: 1,
      type: "table",
    },
    {
      Version: "0.1",
      Event: "Quote",
      Metadata: "Model",
      DisplayName: "Model",
      AggregationMode: "Value",
      Limit: 1,
      type: "table",
    },
    {
      Version: "0.1",
      Event: "Quote",
      Metadata: "ltv",
      DisplayName: "LTV",
      AggregationMode: "Value",
      Limit: 1,
      type: "table",
    },
    {
      Version: "0.1",
      Event: "Quote",
      Metadata: "License Plate",
      DisplayName: "License Plate",
      AggregationMode: "Value",
      Limit: 1,
      type: "table",
    },
    {
      Version: "0.1",
      Event: "Quote",
      Metadata: "firstName",
      DisplayName: "First Name",
      AggregationMode: "Value",
      tag: "name",
      Limit: 1,
      type: "inline",
    },
    {
      Version: "0.1",
      Event: "Entered ZipCode",
      Metadata: "zipCode",
      DisplayName: "Zip Code",
      AggregationMode: "Value",
      Limit: 1,
      type: "table",
    },
    {
      Version: "0.1",
      Event: "Quote",
      Metadata: "street",
      DisplayName: "Street",
      AggregationMode: "Value",
      Limit: 1,
      type: "table",
    },
    {
      Version: "0.1",
      Event: "Quote",
      Metadata: "apt",
      DisplayName: "Apt",
      Limit: 1,
      AggregationMode: "Value",
      type: "table",
    },
    {
      Version: "0.1",
      Event: "Quote",
      Metadata: "city",
      DisplayName: "City",
      Limit: 1,
      AggregationMode: "Value",
      type: "table",
    },
    {
      Version: "0.1",
      Event: "Quote",
      Limit: 1,
      Metadata: "lastName",
      DisplayName: "Last Name",
      AggregationMode: "Value",
      tag: "name",
      type: "inline",
    },
  ],
};
